import cardPixinguinhaImg from "./images/card-pixinguinha.jpeg";
import cardPortoCariocaImg from "./images/card-porto-carioca.jpg";
import cardCaminhosDaGuanabara from "./images/card-caminhos-da-guanabara.jpeg";
import cardArcosPortoImg from "./images/card-arcos-do-porto.jpeg.webp";
import cardCiataResidencialImg from "./images/card-ciata.png";
import cardNovaOlariaImg from "./images/card-nova-olaria-fachada.png";
import cardOrlaMauaImg from "./images/cad-orla-maua-piscina-roof-top.png";
import cardMetropolitanDreamBarraImg from "./images/card-metropolitan-dream-vista-aerea.png";
import cardAmericas19Img from "./images/card-americas-19-fachada.jpeg.webp";
import cardOrlaRecreioPontalImg from "./images/card-orla-praia-pontal-psicina.png";
import cardThePierImg from "./images/card-the-pier-vista-eterna-baia.png";
import { Imovel } from "../imoveis";

// **AQUI É ONDE VOCÊ DEVE ADICIONAR NOVOS CARDS DE LANÇAMENTOS**
// Para adicionar um novo lançamento, copie este padrão:
export const lancamentos: Imovel[] = [
  {
    id: "1",
    titulo: "Residencial Pixinguinha",
    descricao: "Studios, quartos com opção de suíte e vaga lazer completo com rooftop",
    preco: "A partir de R$ 310.000",
    imagem: cardPixinguinhaImg,
    regiao: "Porto Maravilha",
    quartos: 3,
    area: "83,63m²",
    url: "/porto-maravilha/lancamento/pixinguinha",
    destaque: true,
    regiaoDestaque: true,
    tipo: "lancamento",
  },
  {
    id: "2",
    titulo: "Porto Carioca",
    descricao: "O Porto Carioca é um empreendimento projetado para proporcionar segurança, lazer e comodidade a todos os seus moradores",
    preco: "A partir de R$ 449.060",
    imagem: cardPortoCariocaImg,
    regiao: "Porto Maravilha",
    quartos: 3,
    area: "85,26m²",
    url: "/porto-maravilha/lancamento/porto-carioca",
    destaque: true,
    tipo: "lancamento",
  },
  {
    id: "3",
    titulo: "Caminhos da Guanabara",
    descricao: "Um manifesto em forma de arte e arquitetura que preenche Niterói. Onde todos seus caminhos se encontram.",
    preco: "A partir de R$ 260.323",
    imagem: cardCaminhosDaGuanabara,
    regiao: "Niterói",
    quartos: 2,
    area: "51,30m²",
    url: "/lancamentos/caminhos-da-guanabara",
    destaque: true,
    regiaoDestaque: true,
    tipo: "lancamento",
  },
  {
    id: "4",
    titulo: "Arcos do Porto",
    descricao: "A melhor forma de viver o Rio. Lazer completo no coração do Porto Maravilha com opções de Studio a Garden.",
    preco: "A partir de R$ 336.396",
    imagem: cardArcosPortoImg,
    regiao: "Porto Maravilha",
    quartos: 2,
    area: "59,08m²",
    url: "/lancamentos/arcos-do-porto",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "5",
    titulo: "Ciata Residencial",
    descricao: "Cultura • Conexão • Legado. Uma homenagem a Tia Ciata no coração do Porto Maravilha, onde nasceu o samba.",
    preco: "A partir de R$ 325.455",
    imagem: cardCiataResidencialImg,
    regiao: "Porto Maravilha",
    quartos: 2, 
    area: "39,65m²",
    url: "/lancamentos/ciata-residencial",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "6",
    titulo: "Nova Olaria",
    descricao: "Tradição e modernidade se encontram. Uma nova forma de viver, morar e pertencer no coração de Olaria.",
    preco: "A partir de R$ 259.430",
    imagem: cardNovaOlariaImg,
    regiao: "Olaria",
    quartos: 2,
    area: "41,34m²",
    url: "/lancamentos/nova-olaria",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "7",
    titulo: "Orla Mauá",
    descricao: "O coração pulsante da vida urbana carioca. Viva no Boulevard Olímpico com vista para o Museu do Amanhã.",
    preco: "A partir de R$ 721.407",
    imagem: cardOrlaMauaImg,
    regiao: "Porto Maravilha",
    quartos: 3, 
    area: "76,56m²",
    url: "/lancamentos/orla-maua",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "8",
    titulo: "Metropolitan Dream Barra",
    descricao: "Mega complexo com 5 torres e lazer completo na Barra da Tijuca. Viva o seu dream living com bar da piscina, rooftop e localização premium.",
    preco: "A partir de R$ 334.588",
    imagem: cardMetropolitanDreamBarraImg,
    regiao: "Barra da Tijuca",
    quartos: 3, 
    area: "79,74m²",
    url: "/lancamentos/metropolitan-dream-barra",
    destaque: true,
    regiaoDestaque: true,
    tipo: "lancamento",
  },
  {
    id: "9",
    titulo: "Américas19",
    descricao: "Bem-vindo ao melhor jeito de viver no Recreio. Localização premium no melhor quilômetro da Av. das Américas.",
    preco: "A partir de R$ 452.610",
    imagem: cardAmericas19Img,
    regiao: "Recreio dos Bandeirantes",
    quartos: 3,
    area: "136,25m²",
    url: "/lancamentos/americas19",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "10",
    titulo: "Orla Recreio",
    descricao: "Vista para o mar + Lazer completo. Viva o ano inteiro como em férias na Praia do Pontal, Recreio dos Bandeirantes.",
    preco: "A partir de R$ 401.314",
    imagem: cardOrlaRecreioPontalImg,
    regiao: "Recreio dos Bandeirantes",
    quartos: 3,
    area: "67,98m²",
    url: "/lancamentos/orla-recreio-pontal",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  {
    id: "11",
    titulo: "The Pier Residencial",
    descricao: "Vista eterna para a Baía de Guanabara no coração de Niterói. Rooftop premium com 5 áreas distintas.",
    preco: "A partir de R$ 337.730",
    imagem: cardThePierImg,
    regiao: "Centro, Niterói",
    quartos: 3, // 1 a 3 quartos (começando com 1)
    area: "57,12m²",
    url: "/lancamentos/the-pier-residencial",
    destaque: false,
    regiaoDestaque: false,
    tipo: "lancamento",
  },
  // **FINAL DA ÁREA DE ADIÇÃO - quando adicionar novos cards, coloque-os aqui seguindo este padrão**
];
