import cardPixinguinhaImg from "./images/card-pixinguinha.jpeg";
import cardPortoCariocaImg from "./images/card-porto-carioca.jpg";
import { Imovel } from "../imoveis";

export const lancamentos: Imovel[] = [
  {
    id: "1",
    titulo: "Residencial Pixinguinha",
    descricao: "Apartamentos modernos no coração do Porto Maravilha",
    preco: "A partir de R$ 294.900",
    imagem: cardPixinguinhaImg,
    regiao: "Porto Maravilha",
    quartos: 2,
    area: "45m²",
    url: "/porto-maravilha/lancamento/pixinguinha",
    destaque: true,
    tipo: "lancamento",
  },
  {
    id: "2",
    titulo: "Porto Carioca",
    descricao: "Apartamentos modernos no coração do Porto Maravilha",
    preco: "A partir de R$ 294.900",
    imagem: cardPortoCariocaImg,
    regiao: "Porto Maravilha",
    quartos: 3,
    area: "85m²",
    url: "/porto-maravilha/lancamento/porto-carioca",
    destaque: true,
    tipo: "lancamento",
  },
  {
    id: "3",
    titulo: "Paradise Garden",
    descricao: "Tranquilidade e natureza no Recreio",
    preco: "A partir de R$ 380.000",
    imagem:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop",
    regiao: "Recreio dos Bandeirantes",
    quartos: 2,
    area: "65m²",
    url: "/recreio/lancamento/paradise",
    destaque: false,
    tipo: "lancamento",
  },
  {
    id: "4",
    titulo: "Ipanema Premium",
    descricao: "Luxo e sofisticação no coração de Ipanema",
    preco: "A partir de R$ 680.000",
    imagem:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    regiao: "Ipanema",
    quartos: 2,
    area: "70m²",
    url: "#",
    destaque: false,
    tipo: "lancamento",
  },
  {
    id: "5",
    titulo: "Tijuca Residencial",
    descricao: "Apartamentos familiares na Tijuca",
    preco: "A partir de R$ 350.000",
    imagem:
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
    regiao: "Tijuca",
    quartos: 3,
    area: "75m²",
    url: "#",
    destaque: false,
    tipo: "lancamento",
  },
  {
    id: "6",
    titulo: "Recreio Family",
    descricao: "Ideal para famílias no Recreio dos Bandeirantes",
    preco: "A partir de R$ 480.000",
    imagem:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
    regiao: "Recreio dos Bandeirantes",
    quartos: 3,
    area: "90m²",
    url: "#",
    destaque: false,
    tipo: "lancamento",
  },
  {
    id: "7",
    titulo: "Copacabana Studio",
    descricao: "Studios modernos em Copacabana",
    preco: "A partir de R$ 280.000",
    imagem:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
    regiao: "Porto Maravilha",
    quartos: 1,
    area: "28m²",
    url: "#",
    destaque: false,
    tipo: "lancamento",
  },
];
